### ISSUE TITLE
LandingPage bei nicht erfolgreicher Suche

### ISSUE THREAD

**Issue by bkroll176** [martinvirtel/dpa-infocom-faq-website-2#10]
Auf dieser Seite müssen auch noch die Kontaktdaten eingefügt werden.
![bildschirmfoto 2017-10-05 um 16 50 45](https://user-images.githubusercontent.com/25816437/31233603-534b683c-a9ed-11e7-85f1-f9b7b241a9e7.png)
![bildschirmfoto 2017-10-05 um 16 51 43](https://user-images.githubusercontent.com/25816437/31233616-5cd57d34-a9ed-11e7-9a13-9be782213999.png)

**Comment by martinvirtel** [comment]
Der Text steht in contact.md - bitte trag' da ein, was Du möchtest (Tel-Nr, E-Mail) und einen höflichen oder netten Text vielleicht.

**Comment by martinvirtel** [comment]
Self-Service ;-)

**Comment by martinvirtel** [comment]
Self-Service ;-)

**Comment by martinvirtel** [comment]
Kontaktdaten sowohl für das Overlay (Klick auf die Sprechblase) als auch für diese Seite steht in `_include/contact_details.html` .
