### ISSUE TITLE
Symbol austauschen / Herz -> Sprechblase ("Feedback")

### ISSUE THREAD

**Issue by bkroll176** [martinvirtel/dpa-infocom-faq-website-2#2]
![bildschirmfoto 2017-10-05 um 14 13 16](https://user-images.githubusercontent.com/25816437/31226664-414d1b5a-a9d7-11e7-8d58-165293aaa855.png)

Auf dem Overlay: E-Mail-Formular oder klickbare E-Mail-Adresse (an: service@dpa-info.com) oder dpa-Infocom-Servicedesk  040 - 4113 - 31000

**Comment by martinvirtel** [comment]
Erledigt ;-)
